import 'data/model.dart';

List<dataset> data_test = <dataset>[
  dataset(
      id: 0,
      f01: 'A-test',
      f02: 'B-test',
      f03: 'C-test',
      f04: 'D-test',
      f05: 'E-test',
      f06: 'F-test'),
  dataset(
      id: 1,
      f01: 'G-test',
      f02: 'H-test',
      f03: 'I-test',
      f04: 'J-test',
      f05: 'K-test',
      f06: 'L-test'),
  dataset(
      id: 2,
      f01: 'M-test',
      f02: 'N-test',
      f03: 'O-test',
      f04: 'P-test',
      f05: 'Q-test',
      f06: 'R-test'),
  dataset(
      id: 3,
      f01: 'S-test',
      f02: 'T-test',
      f03: 'U-test',
      f04: 'V-test',
      f05: 'W-test',
      f06: 'X-test'),
  dataset(
      id: 4,
      f01: 'A-test',
      f02: 'B-test',
      f03: 'C-test',
      f04: 'D-test',
      f05: 'E-test',
      f06: 'F-test'),
  dataset(
      id: 5,
      f01: 'G-test',
      f02: 'H-test',
      f03: 'I-test',
      f04: 'J-test',
      f05: 'K-test',
      f06: 'L-test'),
  dataset(
      id: 6,
      f01: 'M-test',
      f02: 'N-test',
      f03: 'O-test',
      f04: 'P-test',
      f05: 'Q-test',
      f06: 'R-test'),
  dataset(
      id: 7,
      f01: 'S-test',
      f02: 'T-test',
      f03: 'U-test',
      f04: 'V-test',
      f05: 'W-test',
      f06: 'X-test'),
  dataset(
      id: 8,
      f01: 'M-test',
      f02: 'N-test',
      f03: 'O-test',
      f04: 'P-test',
      f05: 'Q-test',
      f06: 'R-test'),
  dataset(
      id: 9,
      f01: 'S-test',
      f02: 'T-test',
      f03: 'U-test',
      f04: 'V-test',
      f05: 'W-test',
      f06: 'X-test'),
  dataset(
      id: 10,
      f01: 'A-test',
      f02: 'B-test',
      f03: 'C-test',
      f04: 'D-test',
      f05: 'E-test',
      f06: 'F-test'),
  dataset(
      id: 11,
      f01: 'G-test',
      f02: 'H-test',
      f03: 'I-test',
      f04: 'J-test',
      f05: 'K-test',
      f06: 'L-test'),
];

// List<Dessert> data_test = [];
